metadata:
  namespace:
  #baf
  name:
  #indy-key-mgmt

network:
  name:

image:
  name:
  #indy-key-mgmt
  repository:
  #indy-key-mgmt:latest

vault:
  address:
  #http://vault:8200
  keyPath:
  #provider.stewards
  identity:
  #my-identity
  admin_auth_path:
  #kubernetes-baf-provider-admin-auth
  policy:
  #baf-provider-steward-1-ro
  policy_content:
  #path "/kv/{{ organization }}/baf-ac/+/+/+/public*" {capabilities = [ "read", "list" ]}
  auth_path:
  #kubernetes-baf-provider-steward-1-auth


account:
  admin_service:
  # baf-provider-admin-vault-auth
  admin_role:
  # rw
  service:
  # provider-steward-1-vault-auth
  role:
  # ro