#############################################################################################
# This role creates value files for service account
#############################################################################################

# Check service account exists already
- name: Check if service account for {{ component_name }} exists
  k8s_facts:
    kind: ServiceAccount
    name: "{{ component_name }}"
    namespace: "{{ component_namespace }}"
    kubeconfig: "{{ kubernetes.config_file }}"
  register: serviceaccount_state

# Create service account
- name: Create service account for {{ component_name }}
  include_role:
    name: create/k8_component
  vars:
    component_type: "service-account"
    component_type_name: "{{ component_name }}"
  when: serviceaccount_state.resources|length == 0

# Check cluster role binding
- name : Check cluster role binding for {{ component_name }}
  k8s_facts:
    kind: ClusterRoleBinding
    name: "{{ component_name }}"
    namespace: "{{ component_namespace }}"
    kubeconfig: "{{ kubernetes.config_file }}"
  register: clusterrolebinding_state

- debug:
  vars:
    component_type: "{{ 'admin-cluster-role-binding' if '{{ component_name }}' == '{{ organization }}-admin-vault-auth' else 'cluster-role-binding' }}"
    component_type_name: "{{ component_name }}"
    msg: debug {{ component_name }} debug {{ component_type }}

# Create cluster role binding
- name: Create cluster role binding for {{ component_name }}
  include_role:
    name: create/k8_component
  vars:
    component_type: "{{ 'admin-cluster-role-binding' if '{{ component_name }}' == '{{ organization }}-admin-vault-auth' else 'cluster-role-binding' }}"
    component_type_name: "{{ component_name }}"
  when: clusterrolebinding_state.resources|length == 0
